### ISSUE TITLE
Not working in Android Studio Electric Eel | 2022.1.1

### ISSUE THREAD

**Issue by wangkunlin** [elitegit/asm-intellij-plugin#10]
java.lang.ClassCastException: class com.android.tools.idea.uibuilder.editor.multirepresentation.sourcecode.SourceCodeEditorWithMultiRepresentationPreview cannot be cast to class com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl (com.android.tools.idea.uibuilder.editor.multirepresentation.sourcecode.SourceCodeEditorWithMultiRepresentationPreview is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @2cebffac; com.intellij.openapi.fileEditor.impl.text.PsiAwareTextEditorImpl is in unnamed module of loader com.intellij.util.lang.PathClassLoader @2471cca7)
	at org.objectweb.asm.idea.plugin.action.ShowBytecodeViewerAction$1.compute(ShowBytecodeViewerAction.java:152)
	at org.objectweb.asm.idea.plugin.action.ShowBytecodeViewerAction$1.compute(ShowBytecodeViewerAction.java:146)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at org.objectweb.asm.idea.plugin.action.ShowBytecodeViewerAction.findClassFile(ShowBytecodeViewerAction.java:146)
	at org.objectweb.asm.idea.plugin.action.ShowBytecodeViewerAction.lambda$actionPerformed$1(ShowBytecodeViewerAction.java:120)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by wangkunlin** [comment]
Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.2
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    idea.plugin.protoeditor (221.6095)
    org.ollide.java2smali (1.6)
    PsiViewer (221-SNAPSHOT)
    de.ohmesoftware.parcelablegenerator (0.7.1)
    com.pingfangx.plugin.legacylayoutinspector (1.1.0)
    com.developerphil.adbidea (1.6.8)
    AceJump (3.8.8)
    IdeaVIM (1.10.3)
    ASM Bytecode Viewer (9.2)
